### ISSUE TITLE
Afak Sales

### ISSUE THREAD

**Issue by MohammadSamman** [AmmarFattal/afaksoft#16]
- -------------DONE----------------

- [x] زيادة الكمية بفاتورة البيع
- [x] اشارة وقت ضغط الزر اضف
- [x] سكرول وقت بحث عن حساب بالسند
- [x] تكبير المجموع والصافي بطباعة الفاتورة
- [x] حذف سطر او تعديل سطر اخر سطر دائما
- [x] تفعيل البحث للمواد من الفاتورة مع السماح بتعديل السعر
- [x] في الإعدادات المتقدمة عند وضع اشارة ع تعديل السعر تتفعل تلقائيا api

**Comment by AmmarFattal** [comment]
تم اصلاح جميع المشاكل المذكورة و تم رفع نسخة جديدة رابط التحميل 
afaksoft.com/AfakSales.apk
